### ISSUE TITLE
Explicit whitespace is being ignored

### ISSUE THREAD

**Issue by wychwitch** [lanice/obsidian-rant#1]
Again, thank you so much for this plugin!!! I was experimenting going through the examples and I found out that explicit whitespace is being ignored in the output, I'm not sure if this is an obsidian limitation or what

The example I'm following is [string literals](https://docs.rant-lang.org/language/text.html#string-literals) with the first example

```
"    This text is indented"
```

I'll make more issues as I test this out!

**Comment by lanice** [comment]
Good catch! Just played around with it for a bit, I think that might have to do with how Markdown is represented in general.
It seems like Obsidian trims any arbitrary amount of whitespace down to just a single whitespace, for example if I just type 
```
Hello this           is me
```
without any sort of code block, then in the preview mode it becomes
```
Hello this is me
```
There is probably a way around that, but I'll have to have a deeper look on how these things work :D

**Comment by wychwitch** [comment]
AHH yeah I figured it was something like that!! I've ran into weird whitespace formatting with obsidian before lmao

**Comment by lanice** [comment]
Closing this here, as this is more a Markdown/Obsidian thing than about this plugin.
