### ISSUE TITLE
Syntax error when using dice roller table

### ISSUE THREAD

**Issue by wychwitch** [lanice/obsidian-rant#3]
I'm not sure what's going on with this, it seems all right!

Here's the code

```rant
`dice: [[Name Dice Tables#^names]]`
```

It's very simple I know hahaha. 

And attached is the console log! 

[obsidian.md-1641699851624.log](https://github.com/lanice/obsidian-rant/files/7834427/obsidian.md-1641699851624.log)

Let me know if there's anything else I need to do!

**Comment by lanice** [comment]
This is inside a rant codeblock I assume? If so, you need to wrap it in double quotes, to prevent the rant compiler from trying to compile it as rant-code. Like so:
````markdown
```rant
Name: "`dice: [[Name Dice Tables#^names]]`"
```
````

**Comment by wychwitch** [comment]
LMAO YEP THAT WAS IT!! Thank you!! I should've known it was something as simple as that hahaha

I'm really excited to keep experimenting with this!!! Already I've been able to sync femme name endings with femme pronouns and etc, which is something I've been wanting to include since I first started working on this!
